import 'package:flutter/material.dart';
import 'package:jee_compass/engine/jee_compass.dart';

void main() => runApp(const JeeCompassApp());

class JeeCompassApp extends StatelessWidget {
  const JeeCompassApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'JEE Compass',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        useMaterial3: true,
        colorScheme: ColorScheme.fromSeed(seedColor: const Color(0xFF1B4965)),
      ),
      home: const TodayScreen(),
    );
  }
}

/// Demo data. Replace with the local database in Phase 1 of BUILD_PLAN.md.
class DemoData {
  static final now = DateTime.now();

  static MasteryResult _m(double score, ProgressState state) => MasteryResult(
        score: score,
        signals: const MasterySignals(),
        state: state,
        sampleSize: 12,
      );

  static final concepts = <ConceptContext>[
    ConceptContext(
      conceptId: 'quadratic',
      subjectId: 'math',
      mastery: _m(0.30, ProgressState.weak),
      examRelevance: 1.0,
    ),
    ConceptContext(
      conceptId: 'newton',
      subjectId: 'phy',
      mastery: _m(0.55, ProgressState.needsPractice),
      examRelevance: 0.9,
    ),
    ConceptContext(
      conceptId: 'bonding',
      subjectId: 'chem',
      mastery: _m(0.70, ProgressState.needsPractice),
      examRelevance: 0.8,
    ),
  ];

  static const subjectNames = {
    'math': 'Mathematics',
    'phy': 'Physics',
    'chem': 'Chemistry',
  };

  static const conceptNames = {
    'quadratic': 'Quadratic Equations',
    'newton': "Newton's Laws",
    'bonding': 'Chemical Bonding',
  };
}

class TodayScreen extends StatefulWidget {
  const TodayScreen({super.key});

  @override
  State<TodayScreen> createState() => _TodayScreenState();
}

class _TodayScreenState extends State<TodayScreen> {
  int _minutes = 90;

  DailyMission get _mission => const MissionGenerator().generate(
        profile: StudentProfile(
          userId: 'demo',
          target: ExamTarget.both,
          dailyMinutes: _minutes,
          joinedAt: DemoData.now,
        ),
        concepts: DemoData.concepts,
        subjectNames: DemoData.subjectNames,
        conceptNames: DemoData.conceptNames,
        openMistakeCount: 4,
        now: DemoData.now,
      );

  String get _greeting {
    final h = DateTime.now().hour;
    if (h < 12) return 'Good morning';
    if (h < 17) return 'Good afternoon';
    return 'Good evening';
  }

  @override
  Widget build(BuildContext context) {
    final mission = _mission;
    final theme = Theme.of(context);
    final hours = mission.totalMinutes ~/ 60;
    final mins = mission.totalMinutes % 60;

    return Scaffold(
      body: SafeArea(
        child: ListView(
          padding: const EdgeInsets.fromLTRB(24, 32, 24, 32),
          children: [
            Text('$_greeting 👋', style: theme.textTheme.titleMedium),
            const SizedBox(height: 24),
            Text('Your JEE Mission', style: theme.textTheme.headlineMedium),
            const SizedBox(height: 8),
            Text(
              hours > 0 ? '$hours hr $mins min' : '$mins min',
              style: theme.textTheme.titleLarge?.copyWith(
                color: theme.colorScheme.primary,
              ),
            ),
            const SizedBox(height: 28),
            for (final block in mission.blocks) _BlockTile(block: block),
            const SizedBox(height: 28),
            FilledButton(
              onPressed: () {},
              style: FilledButton.styleFrom(
                minimumSize: const Size.fromHeight(52),
              ),
              child: const Text('Start Mission'),
            ),
            const SizedBox(height: 40),
            Text('How much time today?', style: theme.textTheme.labelLarge),
            const SizedBox(height: 12),
            Wrap(
              spacing: 8,
              children: [30, 60, 90, 120, 180].map((m) {
                return ChoiceChip(
                  label: Text('$m min'),
                  selected: _minutes == m,
                  onSelected: (_) => setState(() => _minutes = m),
                );
              }).toList(),
            ),
            const SizedBox(height: 16),
            Text(
              'The plan above is generated by the adaptive engine, not '
              'hardcoded. Change the time and watch it rebalance.',
              style: theme.textTheme.bodySmall,
            ),
          ],
        ),
      ),
    );
  }
}

class _BlockTile extends StatelessWidget {
  const _BlockTile({required this.block});

  final MissionBlock block;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final isReview = block.kind == MissionBlockKind.mistakeReview;

    return Container(
      margin: const EdgeInsets.only(bottom: 12),
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: isReview
            ? theme.colorScheme.secondaryContainer
            : theme.colorScheme.surfaceContainerHighest,
        borderRadius: BorderRadius.circular(12),
      ),
      child: Row(
        children: [
          Expanded(
            child: Text(block.label, style: theme.textTheme.titleMedium),
          ),
          Text('${block.minutes} min', style: theme.textTheme.bodyMedium),
        ],
      ),
    );
  }
}
